import 'package:flutter/material.dart';
import 'package:kivuli_app/screens/payment_gateway_screen.dart';
import '../logic/system_controller_logic.dart';

class VaultScreen extends StatelessWidget {
  const VaultScreen({super.key});
  
     @override
       Widget build(BuildContext context) {
           return Scaffold(
                 backgroundColor: Colors.black,
                        body: SingleChildScrollView(
                              padding: const EdgeInsets.all(20),
                                      child: Column(
                                                  children: [
                                                   const Icon(Icons.account_balance_wallet, color: Color(0xFFFFD700), size: 60),
                                                     const SizedBox(height: 10),
                                                              const Text("CURRENT_BALANCE", style: TextStyle(color: Colors.grey, fontSize: 10, letterSpacing: 2)),    
                                                                    Text(SystemController.uchumi.balance.toString(),
                                                                                                style: TextStyle(color: Colors.white, fontSize: 28, fontWeight: FontWeight.bold)),

                                                                                                                                    const SizedBox(height: 40),


                                                                                                                                                            const Align(
                                                                                                                                                                   alignment: Alignment.centerLeft,
                                                                                                                                                                                        child: Text("LOCAL_GATEWAYS (KES)", style: TextStyle(color: Color(0xFFFFD700), fontSize: 10, fontWeight: FontWeight.bold)),
                                                                                                                                                                                                                                                                                                                           ),
                                                                                                                                                                                                                                                                    const SizedBox(height: 15),
                                                                                                                                                                                                                                                                                GridView.count(
                                                                                                                                                                                                                                                                                  shrinkWrap: true,
                                                                                                                                                                                                                                                        physics: const NeverScrollableScrollPhysics(),
                                                                                                                                                                                                                                                                      crossAxisCount: 2,
                                                                                                                                                                                                                                                                           crossAxisSpacing: 12,
                                                                                                                                                                                                                                                                                        mainAxisSpacing: 12,
                                                                                                                                                                                                                                                                                              childAspectRatio: 1.3,
                                                                                                                                                                                                                                                                                                                              children: [
                                                                                                                                                                                                                                                                                                                                              _paymentBox(context, "M-PESA", Colors.green, Icons.phone_android),
                                                                                                                                                                                                                                                                                                                                                              _paymentBox(context, "AIRTEL", Colors.red, Icons.signal_cellular_alt),
                                                                                                                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                    
                                                                                                                                                                                                                                                                                                                                                                                                    const SizedBox(height: 30),
                                                    

                                                                                                                                                                                                                                                                                                                                                                                                                            const Align(
                                                                                                                                                                                                                                                                                                                                                                                                                                          alignment: Alignment.centerLeft,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        child: Text("GLOBAL_NETWORKS (USD \$)", style: TextStyle(color: Colors.grey, fontSize: 10, fontWeight: FontWeight.bold)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const SizedBox(height: 15),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            GridView.count(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          shrinkWrap: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        physics: const NeverScrollableScrollPhysics(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         crossAxisCount: 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   crossAxisSpacing: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          mainAxisSpacing: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                childAspectRatio: 1.3,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              _paymentBox(context, "MINI PAY", Colors.green, Icons.wallet),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              _paymentBox(context, "GOOGLE PAY", Colors.white, Icons.account_balance),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              _paymentBox(context, "PAYPAL", Colors.blueAccent, Icons.payment),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Widget _paymentBox(BuildContext context, String title, Color color, IconData icon) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return InkWell(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onTap: () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Navigation.push(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  context,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  MaterialPageRouter(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    builder: (context) => PaymentGatewayScreen(method: title, themeColor: color),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              child:Container(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                decoration: BoxDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  colour: const Color(0xFF0F0F0F),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: BorderRadius.circular(15),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                child:Column(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  mainAxisAlignment: MainAxisAlignment.center,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Icon(icon,color:color, size: 30),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const SizedBox(height: 10),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Text(title, style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 11)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
}
  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                    



                                                    

                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                        u                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
